name: HeroesDungeon
version: '${version}'
main: net.brian.heroesdungeon.HeroesDungeon
api-version: 1.18
commands:
  HeroesDungeon:
    aliases:
      - dungeon
      - hd
depend:
  - SlimeWorldManager
  - PlayerDataSync
softdepend:
  - MythicMobs
  - ScriptedQuests